publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2"]
    pos1: [1.57, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos2: [-1.57, 0.0, 0.0, 0.0, 0.0, 0.0]

    joints:
      - shoulder_lift_joint
      - shoulder_pan_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_lift_joint: [0,0]
      shoulder_pan_joint: [0,0]
      elbow_joint: [0,0]
      wrist_1_joint: [0,0]
      wrist_2_joint: [0,0]
      wrist_3_joint: [0,0]

